// <auto-generated />
using System;
using KozlovAppV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KozlovAppV2.Migrations
{
    [DbContext(typeof(User13Context))]
    [Migration("20230304112410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KozlovAppV2.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("OrderDeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderPickupPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__C3905BAF09CA5FBE");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("KozlovAppV2.Models.Product", b =>
                {
                    b.Property<string>("ProductArticleNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProductCost")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ProductDiscountAmount")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProductManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProductPhoto")
                        .HasColumnType("image");

                    b.Property<int?>("ProductQuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("ProductStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductArticleNumber")
                        .HasName("PK__Product__2EA7DCD514801448");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("KozlovAppV2.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A0CB3FCDB");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("KozlovAppV2.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPatronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCAC4D8C8B63");

                    b.HasIndex("UserRole");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("ProductArticleNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrderId", "ProductArticleNumber")
                        .HasName("PK__OrderPro__817A26626B9A4E27");

                    b.HasIndex("ProductArticleNumber");

                    b.ToTable("OrderProduct", (string)null);
                });

            modelBuilder.Entity("KozlovAppV2.Models.User", b =>
                {
                    b.HasOne("KozlovAppV2.Models.Role", "UserRoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("UserRole")
                        .IsRequired()
                        .HasConstraintName("FK__User__UserRole__398D8EEE");

                    b.Navigation("UserRoleNavigation");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("KozlovAppV2.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderProd__Order__403A8C7D");

                    b.HasOne("KozlovAppV2.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductArticleNumber")
                        .IsRequired()
                        .HasConstraintName("FK__OrderProd__Produ__412EB0B6");
                });

            modelBuilder.Entity("KozlovAppV2.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
